=== max-ieremenko/ThirdPartyLibraries/Docs/schema.license-index.json
{
    "$schema": "https://json-schema.org/draft-04/schema",
    "id": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.license-index.json",
    "title": "License index file",
    "description": "License description file.",
    "type": "object",
    "required": [
        "Code",
        "FullName",
        "HRef",
        "FileName"
    ],
    "properties": {
        "Code": {
            "type": "string",
            "description": "The license code, for some web api is case sensitive."
        },
        "FullName": {
            "type": "string",
            "description": "The license full name."
        },
        "RequiresApproval": {
            "type": "boolean",
            "description": "The flag allows marking a package with this license as AutomaticallyApproved.",
            "default": false
        },
        "RequiresThirdPartyNotices": {
            "type": "boolean",
            "description": "The flag indicates that a package with this license should contain extra text in ThirdPartyNotices.txt",
            "default": false
        },
        "HRef": {
            "type": "string",
            "format": "uri",
            "description": "The link to the license content."
        },
        "FileName": {
            "type": "string",
            "description": "The name of the file in this folder, a copy of the license content, is used to generate third-party notices."
        },
        "Dependencies": {
            "type": "array",
            "description": "An array of license codes on which the license depends.",
            "items": {
                "type": "string"
            }
        }
    }
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/licenses/cc-by-3.0/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.license-index.json",
  "Code": "CC-BY-3.0",
  "FullName": "Creative Commons Attribution 3.0 Unported",
  "RequiresApproval": true,
  "HRef": "https://spdx.org/licenses/CC-BY-3.0",
  "FileName": "license.txt"
}
