=== max-ieremenko/ThirdPartyLibraries/Docs/schema.package-index.json
{
    "$schema": "https://json-schema.org/draft-04/schema",
    "id": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
    "title": "Package reference index file",
    "type": "object",
    "required": [
        "License",
        "UsedBy",
        "Licenses"
    ],
    "properties": {
        "Source": {
            "type": "string",
            "format": "uri",
            "description": "Link to the source from which the package was downloaded."
        },
        "License": {
            "type": "object",
            "description": "Conclusion about the package license.",
            "required": [
                "Code",
                "Status"
            ],
            "properties": {
                "Code": {
                    "type": "string",
                    "description": "The license code."
                },
                "Status": {
                    "enum": [
                        "HasToBeApproved",
                        "AutomaticallyApproved",
                        "Approved"
                    ],
                    "description": "The conclusion status."
                }
            }
        },
        "UsedBy": {
            "type": "array",
            "description": "List of applications that use this package.",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "Name"
                ],
                "properties": {
                    "Name": {
                        "type": "string",
                        "description": "The name of the application."
                    },
                    "InternalOnly": {
                        "type": "boolean",
                        "description": "The flag indicates that the package is internal reference and will not be listed in third-party notices."
                    },
                    "TargetFrameworks": {
                        "type": "array",
                        "description": "The list of target frameworks of projects that use this package.",
                        "items": {
                            "type": "string"
                        }
                    },
                    "Dependencies": {
                        "type": "array",
                        "description": "The list of package dependencies.",
                        "items": {
                            "type": "object",
                            "required": [
                                "Name",
                                "Version"
                            ],
                            "properties": {
                                "Name": {
                                    "type": "string",
                                    "description": "Dependent package name."
                                },
                                "Version": {
                                    "type": "string",
                                    "description": "Dependent package version."
                                }
                            }
                        }
                    }
                }
            }
        },
        "Licenses": {
            "type": "array",
            "description": "The list of found package licenses.",
            "items": {
                "type": "object",
                "required": [
                    "Subject",
                    "Code",
                    "HRef"
                ],
                "properties": {
                    "Subject": {
                        "enum": [
                            "package",
                            "homepage",
                            "repository",
                            "project"
                        ],
                        "description": "Subject of found license."
                    },
                    "Code": {
                        "type": "string",
                        "description": "The license code."
                    },
                    "HRef": {
                        "type": "string",
                        "format": "uri",
                        "description": "The link to the license content."
                    },
                    "Description": {
                        "type": "string",
                        "description": "The hint by ThirdPartyLibraries tool."
                    }
                }
            }
        }
    }
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.net.test.sdk/17.12.0/index.json
{
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net8.0",
        "net9.0"
      ],
      "Dependencies": [
        {
          "Name": "Microsoft.CodeCoverage",
          "Version": "17.12.0"
        },
        {
          "Name": "Microsoft.TestPlatform.TestHost",
          "Version": "17.12.0"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.sourcelink.github/8.0.0/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net10.0",
        "net8.0",
        "net9.0",
        "netstandard2.1"
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/dotnet/sourcelink"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/dotnet/sourcelink"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.codecoverage/17.12.0/index.json
{
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net8.0",
        "net9.0"
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.testing.platform.msbuild/1.5.3/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net8.0",
        "net9.0"
      ],
      "Dependencies": [
        {
          "Name": "Microsoft.Testing.Platform",
          "Version": "1.5.3"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/testfx"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/testfx"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/richardszalay.mockhttp/7.0.0/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "netstandard2.1"
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/richardszalay/mockhttp"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.testing.extensions.vstestbridge/1.9.0/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net10.0",
        "net8.0",
        "net9.0"
      ],
      "Dependencies": [
        {
          "Name": "Microsoft.TestPlatform.AdapterUtilities",
          "Version": "17.13.0"
        },
        {
          "Name": "Microsoft.TestPlatform.ObjectModel",
          "Version": "18.0.1"
        },
        {
          "Name": "Microsoft.Testing.Extensions.Telemetry",
          "Version": "1.9.0"
        },
        {
          "Name": "Microsoft.Testing.Extensions.TrxReport.Abstractions",
          "Version": "1.9.0"
        },
        {
          "Name": "Microsoft.Testing.Platform",
          "Version": "1.9.0"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/testfx"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/testfx"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.testplatform.testhost/17.9.0/index.json
{
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net6.0",
        "net7.0",
        "net8.0"
      ],
      "Dependencies": [
        {
          "Name": "Microsoft.TestPlatform.ObjectModel",
          "Version": "17.9.0"
        },
        {
          "Name": "Newtonsoft.Json",
          "Version": "13.0.3"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "LICENSE_MIT.txt",
      "Description": "The license file is identical to the repository license file."
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/microsoft.testplatform.testhost/18.5.1/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "net10.0",
        "net8.0",
        "net9.0"
      ],
      "Dependencies": [
        {
          "Name": "Microsoft.TestPlatform.ObjectModel",
          "Version": "18.5.1"
        },
        {
          "Name": "Newtonsoft.Json",
          "Version": "13.0.3"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/microsoft/vstest"
    }
  ]
}
