=== max-ieremenko/ThirdPartyLibraries/Docs/schema.package-index.json
{
    "$schema": "https://json-schema.org/draft-04/schema",
    "id": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
    "title": "Package reference index file",
    "type": "object",
    "required": [
        "License",
        "UsedBy",
        "Licenses"
    ],
    "properties": {
        "Source": {
            "type": "string",
            "format": "uri",
            "description": "Link to the source from which the package was downloaded."
        },
        "License": {
            "type": "object",
            "description": "Conclusion about the package license.",
            "required": [
                "Code",
                "Status"
            ],
            "properties": {
                "Code": {
                    "type": "string",
                    "description": "The license code."
                },
                "Status": {
                    "enum": [
                        "HasToBeApproved",
                        "AutomaticallyApproved",
                        "Approved"
                    ],
                    "description": "The conclusion status."
                }
            }
        },
        "UsedBy": {
            "type": "array",
            "description": "List of applications that use this package.",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "Name"
                ],
                "properties": {
                    "Name": {
                        "type": "string",
                        "description": "The name of the application."
                    },
                    "InternalOnly": {
                        "type": "boolean",
                        "description": "The flag indicates that the package is internal reference and will not be listed in third-party notices."
                    },
                    "TargetFrameworks": {
                        "type": "array",
                        "description": "The list of target frameworks of projects that use this package.",
                        "items": {
                            "type": "string"
                        }
                    },
                    "Dependencies": {
                        "type": "array",
                        "description": "The list of package dependencies.",
                        "items": {
                            "type": "object",
                            "required": [
                                "Name",
                                "Version"
                            ],
                            "properties": {
                                "Name": {
                                    "type": "string",
                                    "description": "Dependent package name."
                                },
                                "Version": {
                                    "type": "string",
                                    "description": "Dependent package version."
                                }
                            }
                        }
                    }
                }
            }
        },
        "Licenses": {
            "type": "array",
            "description": "The list of found package licenses.",
            "items": {
                "type": "object",
                "required": [
                    "Subject",
                    "Code",
                    "HRef"
                ],
                "properties": {
                    "Subject": {
                        "enum": [
                            "package",
                            "homepage",
                            "repository",
                            "project"
                        ],
                        "description": "Subject of found license."
                    },
                    "Code": {
                        "type": "string",
                        "description": "The license code."
                    },
                    "HRef": {
                        "type": "string",
                        "format": "uri",
                        "description": "The link to the license content."
                    },
                    "Description": {
                        "type": "string",
                        "description": "The hint by ThirdPartyLibraries tool."
                    }
                }
            }
        }
    }
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/emptyfiles/4.4.0/index.json
{
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "netstandard2.1"
      ],
      "Dependencies": [
        {
          "Name": "System.Memory",
          "Version": "4.6.0"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/SimonCropp/EmptyFiles.git"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/SimonCropp/EmptyFiles"
    }
  ]
}

=== max-ieremenko/ThirdPartyLibraries/ThirdPartyLibraries/packages/nuget.org/diffengine/11.3.0/index.json
{
  "$schema": "https://raw.githubusercontent.com/max-ieremenko/ThirdPartyLibraries/refs/heads/master/Docs/schema.package-index.json",
  "Source": "https://api.nuget.org/v3/index.json",
  "License": {
    "Code": "MIT",
    "Status": "AutomaticallyApproved"
  },
  "UsedBy": [
    {
      "Name": "ThirdPartyLibraries",
      "InternalOnly": true,
      "TargetFrameworks": [
        "netstandard2.1"
      ],
      "Dependencies": [
        {
          "Name": "EmptyFiles",
          "Version": "4.4.0"
        },
        {
          "Name": "System.Management",
          "Version": "6.0.1"
        }
      ]
    }
  ],
  "Licenses": [
    {
      "Subject": "package",
      "Code": "MIT",
      "HRef": "https://licenses.nuget.org/MIT"
    },
    {
      "Subject": "repository",
      "Code": "MIT",
      "HRef": "https://github.com/VerifyTests/DiffEngine.git"
    },
    {
      "Subject": "project",
      "Code": "MIT",
      "HRef": "https://github.com/VerifyTests/DiffEngine"
    }
  ]
}
